from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
from typing import Any


def _read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _read_public_manifest(path: Path) -> dict[str, dict[str, str]]:
    if not path.exists():
        return {}
    with path.open("r", encoding="utf-8", newline="") as handle:
        return {row.get("dataset_id", ""): row for row in csv.DictReader(handle, delimiter="\t")}


def _fmt_bytes(value: int | float | None) -> str:
    size = float(value or 0)
    for unit in ["B", "KB", "MB", "GB", "TB"]:
        if size < 1024 or unit == "TB":
            return f"{size:.1f} {unit}" if unit != "B" else f"{int(size)} B"
        size /= 1024
    return f"{size:.1f} TB"


def _target_rows(summary: dict[str, Any], manifest_rows: dict[str, dict[str, str]]) -> list[str]:
    rows = [
        "| Dataset | Accession/ID | Source | Status | Manifest rows | Raw files | NPZ files |",
        "| --- | --- | --- | --- | ---: | ---: | ---: |",
    ]
    for target in summary.get("public_data_targets", []):
        dataset_id = target.get("dataset_id", "")
        source = manifest_rows.get(dataset_id, {})
        manifest_rows_count = target.get("manifest", {}).get("rows", 0) or (
            target.get("available_manifest") or {}
        ).get("rows", 0)
        rows.append(
            "| {dataset} | {accession} | {source_url} | {stage} | {rows} | {raw} | {npz} |".format(
                dataset=dataset_id,
                accession=source.get("accession_or_doi", ""),
                source_url=source.get("source_url", ""),
                stage=target.get("stage", ""),
                rows=manifest_rows_count,
                raw=target.get("raw_files", {}).get("file_count", 0),
                npz=target.get("npz_files", {}).get("file_count", 0),
            )
        )
    return rows


def _corpus_rows(summary: dict[str, Any]) -> list[str]:
    rows = [
        "| File | Exists | Size |",
        "| --- | --- | ---: |",
    ]
    for corpus in summary.get("corpora", []):
        rows.append(
            f"| `{corpus.get('path')}` | {bool(corpus.get('exists'))} | {_fmt_bytes(corpus.get('bytes'))} |"
        )
    return rows


def _fair_rows(summary: dict[str, Any]) -> list[str]:
    gates = summary.get("publication_gates", {})
    public_ready = bool(gates.get("public_data_ingested"))
    snow_ready = bool(gates.get("snow_lotus_scRNA_present"))
    full_corpus_ready = any(
        corpus.get("path", "").endswith("plant_foundation_corpus_public_mlm.h5ad")
        and corpus.get("exists")
        for corpus in summary.get("corpora", [])
    )
    rows = [
        "| FAIR item | Current status | Action before submission |",
        "| --- | --- | --- |",
        "| Public third-party data identifiers | READY for ingested public accessions | Cite GEO/SRA/DOI records exactly in Methods and Data Availability. |",
        f"| Processed public corpus | {'READY' if full_corpus_ready else 'IN PROGRESS'} | Freeze `data/plant_foundation_corpus_public_mlm.h5ad` and checksum it after all downloads finish. |",
        f"| Snow lotus scRNA/snRNA primary data | {'READY' if snow_ready else 'MISSING'} | Deposit raw FASTQ and processed h5ad/matrix files in GEO/SRA/NGDC/GSA before manuscript submission. |",
        f"| Reusable public-data manifest | {'READY' if public_ready else 'MISSING'} | Keep `data/public_dataset_manifest.tsv` and corpus manifests in the archive. |",
        "| Code and environment | READY as project scripts/configs | Archive a tagged release and include environment/package versions. |",
        "| Figure source data | MISSING | Generate source-data tables for each final figure panel after experiments finish. |",
    ]
    return rows


def write_data_availability_package(
    status_summary: str | Path,
    public_manifest: str | Path,
    output: str | Path,
) -> Path:
    summary = _read_json(Path(status_summary))
    manifest_rows = _read_public_manifest(Path(public_manifest))
    gates = summary.get("publication_gates", {})
    snow_ready = bool(gates.get("snow_lotus_scRNA_present"))
    lines = [
        "# SnowLotus-CellFM Data Availability and FAIR Package",
        "",
        "## Data Availability Draft",
        "",
        "All third-party plant single-cell and supporting transcriptome datasets used by SnowLotus-CellFM are public datasets and are listed in the table below with their GEO/SRA/DOI or repository identifiers. Processed sparse NPZ files, merged AnnData corpora, trained checkpoints, strict split audits, marker-candidate tables, and configuration files are generated by the scripts and manifests archived with this project.",
        "",
    ]
    if snow_ready:
        lines.append(
            "The project includes `data/saussurea_involucrata.h5ad`; before submission, raw sequencing data and the processed AnnData object should be deposited in a community omics repository and cited with the final accession."
        )
    else:
        lines.append(
            "Current blocking item: the project does not yet include `data/saussurea_involucrata.h5ad`. A Nature-level SnowLotus-CellFM manuscript must deposit the raw and processed Saussurea involucrata scRNA/snRNA data in GEO/SRA/ENA/NGDC GSA or an equivalent omics repository before submission."
        )
    lines.extend(
        [
            "",
            "## Public Dataset Inventory",
            "",
            *_target_rows(summary, manifest_rows),
            "",
            "## Corpus Artifacts",
            "",
            *_corpus_rows(summary),
            "",
            "## FAIR Audit",
            "",
            *_fair_rows(summary),
            "",
            "## Repository Actions",
            "",
            "- Freeze a release of the code, configs, manifests, benchmark JSON files, and marker-candidate TSV files.",
            "- Deposit new Saussurea raw reads and processed matrices in a discipline omics repository with a stable accession.",
            "- Include checksums for final merged corpora and checkpoints.",
            "- Cite reused public datasets by accession/DOI in the manuscript reference list and Data Availability statement.",
            "- Add figure source-data tables once final figures are generated.",
            "",
        ]
    )
    output_path = Path(output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")
    print(output_path)
    return output_path


def main() -> None:
    parser = argparse.ArgumentParser(description="Write Data Availability and FAIR materials")
    parser.add_argument("--status-summary", required=True)
    parser.add_argument("--public-manifest", default="data/public_dataset_manifest.tsv")
    parser.add_argument("--output", required=True)
    args = parser.parse_args()
    write_data_availability_package(args.status_summary, args.public_manifest, args.output)


if __name__ == "__main__":
    main()
