#!/usr/bin/env bash
set -euo pipefail
mkdir -p data/public/source_pages
curl -L --retry 5 --connect-timeout 20 --max-time 120 -H 'User-Agent: SnowLotus-CellFM/0.1 public-data-collector' -o data/public/source_pages/scplantdb_global.html https://biobigdata.nju.edu.cn/scplantdb || true
curl -L --retry 5 --connect-timeout 20 --max-time 120 -H 'User-Agent: SnowLotus-CellFM/0.1 public-data-collector' -o data/public/source_pages/scplantllm_reference.html https://github.com/compbioNJU/scPlantLLM || true
curl -L --retry 5 --connect-timeout 20 --max-time 120 -H 'User-Agent: SnowLotus-CellFM/0.1 public-data-collector' -o data/public/source_pages/scplantllm_srp169576_benchmark.html 'https://box.nju.edu.cn/seafhttp/f/66ed8930449d41e98b60/?op=view' || true
curl -L --retry 5 --connect-timeout 20 --max-time 120 -H 'User-Agent: SnowLotus-CellFM/0.1 public-data-collector' -o data/public/source_pages/scplantannotate_reference.html https://doi.org/10.1016/j.jare.2026.01.035 || true
curl -L --retry 5 --connect-timeout 20 --max-time 120 -H 'User-Agent: SnowLotus-CellFM/0.1 public-data-collector' -o data/public/source_pages/vascular_plant_cell_atlas.html https://doi.org/10.1016/j.cell.2025.07.036 || true
curl -L --retry 5 --connect-timeout 20 --max-time 120 -H 'User-Agent: SnowLotus-CellFM/0.1 public-data-collector' -o data/public/source_pages/brassicaceae_multi_species_root_atlas.html https://www.nature.com/articles/s41467-026-73270-2 || true
curl -L --retry 5 --connect-timeout 20 --max-time 120 -H 'User-Agent: SnowLotus-CellFM/0.1 public-data-collector' -o data/public/source_pages/arabidopsis_root_atlas.html 'https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE152766' || true
curl -L --retry 5 --connect-timeout 20 --max-time 120 -H 'User-Agent: SnowLotus-CellFM/0.1 public-data-collector' -o data/public/source_pages/arabidopsis_leaf_atlas.html https://www.psb.ugent.be/sc-leaf-yieldlab/ || true
curl -L --retry 5 --connect-timeout 20 --max-time 120 -H 'User-Agent: SnowLotus-CellFM/0.1 public-data-collector' -o data/public/source_pages/arabidopsis_lifecycle_spatial_atlas.html https://www.nature.com/articles/s41477-025-02072-z || true
curl -L --retry 5 --connect-timeout 20 --max-time 120 -H 'User-Agent: SnowLotus-CellFM/0.1 public-data-collector' -o data/public/source_pages/rice_seedling_atlas.html https://doi.org/10.1016/j.molp.2021.04.005 || true
curl -L --retry 5 --connect-timeout 20 --max-time 120 -H 'User-Agent: SnowLotus-CellFM/0.1 public-data-collector' -o data/public/source_pages/rice_root_tip_atlas.html 'https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE146034' || true
curl -L --retry 5 --connect-timeout 20 --max-time 120 -H 'User-Agent: SnowLotus-CellFM/0.1 public-data-collector' -o data/public/source_pages/rice_soil_stress_root_atlas.html https://www.nature.com/articles/s41586-025-08941-z || true
curl -L --retry 5 --connect-timeout 20 --max-time 120 -H 'User-Agent: SnowLotus-CellFM/0.1 public-data-collector' -o data/public/source_pages/tomato_rice_root_tip_celltype_atlas.html 'https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE149217' || true
curl -L --retry 5 --connect-timeout 20 --max-time 120 -H 'User-Agent: SnowLotus-CellFM/0.1 public-data-collector' -o data/public/source_pages/maize_root_ground_tissue_atlas.html 'https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE172280' || true
curl -L --retry 5 --connect-timeout 20 --max-time 120 -H 'User-Agent: SnowLotus-CellFM/0.1 public-data-collector' -o data/public/source_pages/wheat_soil_root_atlas.html 'https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE270342' || true
curl -L --retry 5 --connect-timeout 20 --max-time 120 -H 'User-Agent: SnowLotus-CellFM/0.1 public-data-collector' -o data/public/source_pages/arabidopsis_secondary_root_dev_atlas.html 'https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE270140' || true
curl -L --retry 5 --connect-timeout 20 --max-time 120 -H 'User-Agent: SnowLotus-CellFM/0.1 public-data-collector' -o data/public/source_pages/catharanthus_leaf_specialized_metabolism.html https://figshare.com/articles/dataset/Single-cell_multi-omics_of_Catharanthus_roseus/20255094 || true
curl -L --retry 5 --connect-timeout 20 --max-time 120 -H 'User-Agent: SnowLotus-CellFM/0.1 public-data-collector' -o data/public/source_pages/cotton_glandular_terpenoid_atlas.html 'https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE243419' || true
curl -L --retry 5 --connect-timeout 20 --max-time 120 -H 'User-Agent: SnowLotus-CellFM/0.1 public-data-collector' -o data/public/source_pages/saussurea_bulk_transcriptome.html https://www.ncbi.nlm.nih.gov/sra/SRX156202%5Baccn%5D || true
curl -L --retry 5 --connect-timeout 20 --max-time 120 -H 'User-Agent: SnowLotus-CellFM/0.1 public-data-collector' -o data/public/source_pages/saussurea_genome_reference.html https://www.ncbi.nlm.nih.gov/bioproject/PRJNA991078 || true
curl -L --retry 5 --connect-timeout 20 --max-time 120 -H 'User-Agent: SnowLotus-CellFM/0.1 public-data-collector' -o data/public/source_pages/saussurea_low_pressure.html https://pmc.ncbi.nlm.nih.gov/articles/PMC11941927/ || true
